<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="8" total="12" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="basic suite" duration-ms="21562" started-at="2019-03-18T06:41:04Z" finished-at="2019-03-18T06:41:26Z">
    <groups>
    </groups>
    <test name="basic test" duration-ms="21562" started-at="2019-03-18T06:41:04Z" finished-at="2019-03-18T06:41:26Z">
      <class name="in.srssprojects.keximbank.TestExecution">
        <test-method status="PASS" signature="browserLaunch()[pri:0, instance:in.srssprojects.keximbank.TestExecution@59f99ea]" name="browserLaunch" is-config="true" duration-ms="8632" started-at="2019-03-18T06:41:04Z" finished-at="2019-03-18T06:41:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserLaunch -->
        <test-method status="PASS" signature="loginTest()[pri:1, instance:in.srssprojects.keximbank.TestExecution@59f99ea]" name="loginTest" duration-ms="2719" started-at="2019-03-18T06:41:13Z" finished-at="2019-03-18T06:41:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="FAIL" signature="roleCreationWithValidData()[pri:2, instance:in.srssprojects.keximbank.TestExecution@59f99ea]" name="roleCreationWithValidData" duration-ms="2605" started-at="2019-03-18T06:41:16Z" finished-at="2019-03-18T06:41:18Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at in.srssprojects.keximbank.TestExecution.roleCreationWithValidData(TestExecution.java:49)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- roleCreationWithValidData -->
        <test-method status="SKIP" signature="roleCreationWithDuplicateData()[pri:3, instance:in.srssprojects.keximbank.TestExecution@59f99ea]" name="roleCreationWithDuplicateData" duration-ms="0" started-at="2019-03-18T06:41:18Z" depends-on-methods="in.srssprojects.keximbank.TestExecution.roleCreationWithValidData" finished-at="2019-03-18T06:41:18Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestExecution.roleCreationWithDuplicateData()[pri:3, instance:in.srssprojects.keximbank.TestExecution@59f99ea] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestExecution.roleCreationWithDuplicateData()[pri:3, instance:in.srssprojects.keximbank.TestExecution@59f99ea] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- roleCreationWithDuplicateData -->
        <test-method status="PASS" signature="logout()[pri:19, instance:in.srssprojects.keximbank.TestExecution@59f99ea]" name="logout" duration-ms="6951" started-at="2019-03-18T06:41:18Z" finished-at="2019-03-18T06:41:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method status="PASS" signature="close()[pri:0, instance:in.srssprojects.keximbank.TestExecution@59f99ea]" name="close" is-config="true" duration-ms="593" started-at="2019-03-18T06:41:25Z" finished-at="2019-03-18T06:41:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- in.srssprojects.keximbank.TestExecution -->
    </test> <!-- basic test -->
  </suite> <!-- basic suite -->
</testng-results>
